siteName = "HRocket"
theme = "HR_Publisher"
disqusShortname = ""
BuilPath = "/home/khurram/hrocket/docs"
publishDir = "/testhrocket"
logoLink = "/"
metaKeywords = "HTML, CSS, XML, XHTML, JavaScript"
googleAnalyticsTrackingId = "UA-232232-34"
siteUrl = "http://example.com"
robotsAllow = "True"

[[mainMenu]]
  name = "Home"
  url = "/testhrocket"
[[mainMenu]]
  name = "About"
  url = "/testhrocket/content/pages/about"
[[mainMenu]]
  name = "Blogs"
  url = "/testhrocket/content/pages/blogs"


[params]
    description = ""
    [params.logo]
      url = "logo.png"
      width = 50
      height = 50
      alt = "Logo"
    [params.favIcon]
      url = "favicon.ico"

